### ISSUE TITLE
Composer Part 1: Layout and Topbar

### ISSUE THREAD

**Issue by FanrayMedia** [FanrayMedia/Fanray#108]
# Overview

This story contains the requirements for Compose.cshtml page (aka composer) which is responsible for adding and editing a post.  The requirements are on **layout**, the **topbar** and **drawer elements**.  The editor is in part 2.

# Layout

The overall layout design of this page is based on this pre-defined [Vuetify layout](https://vuetifyjs.com/en/examples/layouts/googleContacts)

- [x] It should have a **Topbar**, a toolbar on the very top of the page and covers across the whole page.
- [x] Under the toolbar there should be two areas side by side
  - a **Drawer** of form fields to the left
  - an **Editor** area to the right, on the top of the Editor is a **Title** filed

# Topbar overview
- [x] It is implemented as a [Vuetify Toolbar](https://vuetifyjs.com/en/components/toolbars)
- [x] It has the following icon or buttons
  - **Hamburg icon** 
  - **Publish/Update**
  - **Preview**
  - **Save/Saved/Saving**
  - **Close** 

# Topbar buttons

## "Hamburger" icon button

- [x] It should show / hide the **Drawer** when clicking on it.
- [x] The drawer should be open by default when user opens the composer.
- [ ] There should be keyboard shortcut to show / hide the **Drawer**.

## "Publish/Update", "Save/Saved/Saving" and "Close" buttons

There are 3 different conditions the Composer is in at a time.

### Condition 1: When writing a new post

- [x] **Publish** should show instead of **Update**.
- [x] **Publish** button is disabled by default, as soon as you input a value in **Title** field it becomes enabled, and disabled if title becomes empty again.
- [x] When you input text in **Title** or **Editor**
  - [x] 1. **Save** button should show up
  - [x] 2. if user stops typing for 5 seconds, auto-save will save the post to draft
  - [x] 3. during saving **Save** button will be disable and the text will become **Saving** and then **Saved** after save is done
  - [x] 4. if user clicks on Save before auto-save happens, it will behave just as if auto-save happened
- [x] After save (either auto or manual) happens to new post, the URL will update by appending the new post id, for example from `/compose` to `/compose/13`, see [history.replaceState() example?](https://stackoverflow.com/questions/12832317/history-replacestate-example)
- [x] When **Publish** button is clicked, it publishes the post, then it redirects to the single post page.  If the user clicks back button from the single post page, it should go back to admin index page instead of composer (see https://stackoverflow.com/a/35667628/32240).
- [x] When you update any form fields other than **Title** and **Editor**, auto-save should NOT happen, you should see an orange enabled **Save** button should show up.  Clicking on which will save the post to draft, after which the button becomes disabled with **Saved** text.
- [x] When composer is dirty, clicking on **Close** will be warned with message `There are unsaved changes. Are you sure you want to leave?`

### Condition 2: When editing a post that is a draft

It should behave just like Condition 1, except no new post id will be appended to the url.

### Condition 3: When editing a post that is a published

- [x] Auto-save should NOT happen in this condition, thus Save button should not show up at all.  This is because user may not be ready for the changes to a **published** post to show to the public.  It is _recommended_ if user intends to make a lot of changes, user should revert the post back to draft first.
- [x] **Update** button should show up instead of **Publish**.
- [x] **Update** button is disabled by default, as soon as you input a value in **Title** field it becomes enabled, and disabled if title becomes empty again.
- [x] When clicked on **Update** button, the button text should become **Updating** immediately
- [x] **Revert** button should show up, click on it should revert post back to a draft
- [x] When you navigate away (whether by clicking **Close** button or refresh), it will alert you there are unsaved changes.

## "Close" button

- [x] When you navigate away (whether by clicking **Close** button or refresh), it will alert you there are unsaved changes.
- [x] Clicking on the **Close** button should take you back to Admin index page.

# Todos

- Allows comments ( (default), none, open, close )
- Featured image if theme uses it
- Scheduling of a future post

**Comment by FanrayMedia** [comment]
Closing and any left over see #191
