### ISSUE TITLE
Composer Part 2: Editor

### ISSUE THREAD

**Issue by FanrayMedia** [FanrayMedia/Fanray#109]
# Overview
The specs on the editor which is based on quill.
https://dev.to/charrondev/getting-to-know-quilljs---part-1-parchment-blots-and-lifecycle--3e76
https://www.scalablepath.com/blog/using-quill-js-build-wysiwyg-editor-website/
https://stackoverflow.com/questions/38623716/how-to-add-custom-font-sizes-to-quilljs-editor

# Toolbar 

## Customization

- [x] Add custom buttons, twitter, youtube etc., to the existing toolbar, see https://codepen.io/FanrayMedia/pen/rrVyWv

See 
- related: #126
- https://quilljs.com/docs/modules/toolbar/
- https://quilljs.com/guides/how-to-customize-quill/
- https://github.com/quilljs/quill/blob/develop/docs/_includes/full-toolbar.html

## Insert Embeds

See
- Insert Quill Embeds #125 
- https://quilljs.com/guides/cloning-medium-with-parchment/

# Auto Save

When writing a _brand new_ or _draft_ post, after user stops typing for a few seconds (default 5), the editor will auto-save the post into a draft for user.  For published post, auto-save is not enabled because we don't want to publish content user is still modifying on a published post.  If user decides to make lengthy modifications on a published post, it's recommended to `Revert to draft` the post first.

This feature works closely in conjunction with button the the Topbar see #108 

# Positioning 

## Float toolbar
- [x] On long posts the quill toolbar should float at the top right under the topbar instead of scrolling off screen
  - https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sticky_header
  - https://stackoverflow.com/questions/1216114/how-can-i-make-a-div-stick-to-the-top-of-the-screen-once-its-been-scrolled-to

## Center and limit width on content area

- [x] The content area (title + editor) should have the same width as the theme
- [x] The content area should not be affected by whether the drawer is open or closed.

# Image

## Open Media Library

When user clicks on image icon, the media library should open and let user choose which images to insert.

## Upload

- [x] When user opens up the Media Lib, user should be able to upload new images
- [x] User should be able to upload images by drag and drop them, see https://www.npmjs.com/package/quill-image-drop-module

### Resources
- [File Uploading with ASP.NET Core: What Options Do We Have?](http://sikorsky.pro/en/blog/file-uploading-with-aspnet-core-what-options-do-we-have)
- [Uploading File using Ajax in Asp.Net Core](https://stackoverflow.com/questions/46903310/uploading-file-using-ajax-in-asp-net-core)
- https://github.com/quilljs/quill/issues/1400
- https://github.com/quilljs/quill/issues/863

### Stage 1 Select multiple file
- User should be able to click on the image icon on the toolbar and then select multiple image files.
- If a non image file is selected, there should be warning message.
- Image should be able to be resized https://github.com/kensnyder/quill-image-resize-module
- Caption https://stackoverflow.com/a/10128978/32240

### Stage 2 Drag and Drop
- User should be able to do drag and drop image files into the content area.
- This drag drop uses base64, https://github.com/kensnyder/quill-image-drop-module TODO figure out how to hook up to upload

### Stage 3 Add from Media Lib
- When click on the image icon on the toolbar, instead of open the browser file dialog, the media lib modal popup should show up.  On the media modal there should be Add to upload more images, and select existing image.

## Videos

- YouTube can be embeded but TODO needs resize https://github.com/lancetipton/quill-video-resize
- Vimeo embeded is not correct

## Source

https://github.com/zenoamaro/react-quill/issues/219

## Code Block

- https://quilljs.com/docs/modules/syntax/
- https://cdnjs.com/libraries/highlight.js/
- https://github.com/isagalaev/highlight.js/tree/master/src/languages

## Get html content
- https://stackoverflow.com/questions/39519950/convert-quill-delta-to-html
`quill.root.innerHTML`

## Markdown

Worth looking into some markdown things https://patleeman.github.io/quill-markdown-shortcuts/

### Other useful links
- A vuejs + quill component https://github.com/davidroyer/vue2-editor
- Another 
  - http://edwardize.blogspot.com/2018/04/create-quesion-vuejs-and-quilljs-editor.html
  - https://www.youtube.com/watch?v=lKGLhYbO5q4&t=277s

**Comment by FanrayMedia** [comment]
Closing and any left over see #191
