### ISSUE TITLE
Admin Posts.cshtml

### ISSUE THREAD

**Issue by FanrayMedia** [FanrayMedia/Fanray#113]
# Overview

The admin index page redirects to post page and the posts page shows the posts page.  

# Requirements

- [x] on table header shows different post status [Draft, Published] with their post counts
- [x] pagination, arrows to navigate between older and newer posts
- [x] page-size selection, user selects how many rows to see on the table, [25, 50 etc]
- [x] post deletion
- [x] edit link and post link in addition to delete
- [x] Fix header tab not initially selected issue

# TODOs

- Currently I use `history.pushState` when clicking on the tabs (published, draft), when you click back button the content does not sync with URL.  This may or may not be easy to resolve but it is something that I can live with.
- Drafts need pagination from backend, currently I don't do pagination when request drafts.

## Table Header with post statuses

The actual data-table header is hidden with `hide-headers`, need to look into either [toolbar](https://vuetifyjs.com/en/components/toolbars) with buttons or [tabs](https://vuetifyjs.com/en/components/tabs), but for tabs there must have a click event.

## Data Table with posts

The data-table needs to get data from [server side](https://vuetifyjs.com/en/components/data-tables#example-server), as pagination is done on the server side.
