### ISSUE TITLE
Admin Compose.cshtml

### ISSUE THREAD

**Issue by FanrayMedia** [FanrayMedia/Fanray#191]
# Overview

This ticket is to complete Compose page for v1.1

## Tasks left to complete

- [ ] Select the default category on new post
- [ ] Delete post button
- [ ] Preview
- [ ] The default delimiter is "tab" when user inputs a new tag, see if "comma" can be added as a delimiter.

## Related

These are the previous stories I'm closing and left overs are carried to this story

#108 Layout and topbar 
#109 Editor
#145 Drawer
